/**
 * ADMIN (admin panel) — vendor onboarding se monitoring tak.
 *
 * Yaad rakho: admin ab orders ka status **nahi** badal sakta (decision D6).
 */
const {
  TAG,
  E,
  paging,
  describe,
  saveToken,
  saveFirstId,
  saveId,
  expectStatus,
} = require("./shared");

const AUTH_ADMIN = "`Bearer {{adminToken}}` — role `admin`";

const BRANCH_FIELDS = [
  ["name", "string", "no", "`Main Branch` — branch ka label"],
  ["shopOrBuildingNumber", "string", "no", "`24`"],
  ["address", "string", "yes", "`24, PB Road, Near Jayadeva Circle`"],
  ["area", "string", "no", "`Vidyanagar`"],
  ["city", "string", "yes", "`Davangere`"],
  ["district", "string", "yes", "`Davangere`"],
  ["state", "string", "yes", "`Karnataka`"],
  ["country", "string", "no", "`India`"],
  ["zipcode", "string", "yes", "`577001`"],
  ["formattedAddress", "string", "no", "Google se aaya poora address"],
  [
    "coordinates",
    "number[2]",
    "yes",
    "`[14.4644, 75.9218]` = **[latitude, longitude]** — galat order me delivery charge galat aayega",
  ],
  ["isDefault", "boolean", "no", "`true` → isse distance naapi jayegi"],
];

module.exports = [
  // ══════════════════════════════════════════════════════════════
  {
    id: "adm.auth.login",
    group: "01 Auth",
    name: "01 · ⭐ Admin login",
    method: "POST",
    path: "/auth/login",
    auth: null,
    tag: TAG.SAME,
    body: {
      type: "json",
      value: {
        type: "email",
        email: "ricemartnvs@gmail.com",
        password: "Admin@123",
        role: "admin",
        loginType: "password",
      },
    },
    desc: describe({
      tag: TAG.SAME,
      summary: "Admin panel ka login. Token `{{adminToken}}` me apne aap save ho jata hai.",
      auth: "Public",
      when: ["Sabse pehla call."],
      notes: [
        "`role: \"admin\"` bhejna **zaroori** hai — lookup usi se hota hai.",
        "Admin account API se banta hi nahi — seedha DB me banaya jata hai. `POST /auth/register` ab hamesha `user` banata hai (pehle `role` body se accept hota tha, wo hole band kar diya).",
        "**Stage credentials:** `ricemartnvs@gmail.com` / `Admin@123`",
      ],
      fields: [
        ["type", "enum", "yes", "`email`"],
        ["email", "string", "yes", "`ricemartnvs@gmail.com`"],
        ["password", "string", "yes", "`Admin@123`"],
        ["role", "enum", "yes", "`admin`"],
        ["loginType", "enum", "no", "default `password`"],
      ],
      enums: [["role", "`admin` · `staff`", "Panel ke liye `admin`"]],
      errors: [
        ["403", "—", "Wrong password"],
        ["404", "—", "Is email + role=admin ka account nahi hai"],
      ],
    }),
    script: saveToken("adminToken", "adminId"),
  },

  // ══════════════════════════════════════════════════════════════
  {
    id: "adm.vendor.create",
    group: "02 Vendor Management",
    name: "02 · 🆕 ⭐ Vendor banao (user + profile + pehli branch)",
    method: "POST",
    path: "/vendors/create",
    auth: "adminToken",
    tag: TAG.NEW,
    body: {
      type: "json",
      value: {
        shopName: "Nagraj Mart",
        name: "Nagraj",
        email: "nagraj@gmail.com",
        mobile: "8210574144",
        password: "nagraj@123",
        legalName: "Nagraj Traders",
        gstNumber: "29ABCDE1234F1Z5",
        fssaiNumber: "11223344556677",
        supportMobile: "8210574144",
        commissionPercent: 5,
        payout: {
          accountHolder: "Nagraj",
          accountNumber: "1234567890123",
          ifsc: "SBIN0001234",
          upiId: "nagraj@okaxis",
        },
        branch: {
          name: "Main Branch",
          shopOrBuildingNumber: "24",
          address: "24, PB Road, Near Jayadeva Circle",
          area: "Vidyanagar",
          city: "Davangere",
          district: "Davangere",
          state: "Karnataka",
          country: "India",
          zipcode: "577001",
          coordinates: [14.4644, 75.9218],
          isDefault: true,
        },
      },
    },
    desc: describe({
      tag: TAG.NEW,
      summary:
        "Ek hi call me vendor ka **login account + VendorProfile + pehli branch** — teeno bana deta hai.",
      auth: AUTH_ADMIN,
      when: [
        "Onboarding ka **step 1**. Iske bina na branch ban sakti hai na service area.",
      ],
      notes: [
        "**Vendor self-signup nahi karta.** Admin yahan account banata hai aur email/password vendor ko deta hai. Vendor `POST /auth/login` se `role: \"vendor\"` bhej ke login karta hai.",
        "`email` ya `mobile` — **koi ek** zaroori. Dono de sakte ho.",
        "`branch` **required** hai — bina branch ke vendor ka koi matlab nahi, aur `coordinates` ke bina delivery distance nahi nikalti.",
        "Pehli branch apne aap `isDefault: true` ban jati hai aur `profile.defaultLocationId` usi pe set ho jata hai.",
        "`delivery` na bhejo to platform defaults lag jate hain: `isEnabled: false` (charge ₹0) par baaki values bhari hui — `baseCharge 30`, `perKmRate 5`, `perKgRate 1.5`, `minDeliveryCharge 40`, `baseMaxCharge 150`, `freeDeliveryAbove null`, `maxRadiusKm null`.",
        "Vendor ban jane ke baad bhi customers ko kuch nahi dikhta — **service area assign karna abhi baaki hai** (step 07/09).",
        "Response me `vendor` (user), `profile` (VendorProfile) aur `branch` (Location) teeno aate hain. `vendor._id` hi aage ka `vendorId` hai.",
      ],
      fields: [
        ["shopName", "string", "yes", "`Nagraj Mart` — 2 se 120 chars"],
        ["password", "string", "yes", "`nagraj@123` — 6 se 64 chars"],
        ["email", "string", "email ya mobile", "`nagraj@gmail.com`"],
        ["mobile", "string", "email ya mobile", "`8210574144`"],
        ["name", "string", "no", "`Nagraj` — owner ka naam"],
        ["legalName", "string", "no", "`Nagraj Traders` — max 150"],
        ["gstNumber", "string", "no", "`29ABCDE1234F1Z5` — max 20"],
        ["fssaiNumber", "string", "no", "`11223344556677` — max 20"],
        ["supportMobile", "string", "no", "Customer support number"],
        ["logo", "string", "no", "Logo ka URL"],
        ["commissionPercent", "number", "no", "`5` — 0 se 100"],
        ["delivery", "object", "no", "Vendor ki delivery config (na do to defaults)"],
        ["payout", "object", "no", "`accountHolder`, `accountNumber`, `ifsc`, `upiId`"],
        ["branch", "object", "**yes**", "Neeche wali table"],
      ],
      enums: [
        ["status (response)", "`APPROVED` · `SUSPENDED`", "Naya vendor `APPROVED` banta hai"],
        ["branch.type (response)", "`VENDOR_BRANCH`", "Customer address se alag"],
      ],
      errors: [
        ["400", "—", "Is email/mobile ka vendor pehle se hai"],
        E.VALIDATION,
        ["403", "—", "Admin token nahi hai"],
      ],
      extra: [
        "### `branch` object",
        "",
        "| Field | Type | Required | Matlab / sample |",
        "|---|---|---|---|",
        ...BRANCH_FIELDS.map((f) => `| ${f.join(" | ")} |`),
        "",
        "### Onboarding ka poora sequence",
        "",
        "```",
        "02  POST /vendors/create                      → vendorId + branchId",
        "05  GET  /vendors/:id/branches                (optional — extra branch chahiye to 04)",
        "07  GET  /service-areas/lookup?zipcode=577001 → pincode free hai ya nahi (PEHLE ye)",
        "08  POST /vendors/:id/service-areas           → pincode assign  ✅ ab customers ko dikhega",
        "```",
      ].join("\n"),
    }),
    script: [
      "const j = pm.response.json();",
      "const d = j && j.data;",
      "if (d) {",
      '    if (d.vendor && d.vendor._id) pm.environment.set("vendorId", d.vendor._id);',
      '    if (d.branch && d.branch._id) pm.environment.set("branchId", d.branch._id);',
      "}",
      "",
      'pm.test("201 Created", () => pm.response.to.have.status(201));',
    ],
  },

  {
    id: "adm.vendor.getAll",
    group: "02 Vendor Management",
    name: "03 · 🆕 Saare vendors",
    method: "GET",
    path: "/vendors/getAll",
    auth: "adminToken",
    tag: TAG.NEW,
    query: paging([
      { key: "zipcode", value: "577001", description: "⭐ Is pincode ka vendor kaun hai", disabled: true },
      { key: "status", value: "APPROVED", description: "`APPROVED` | `SUSPENDED`", disabled: true },
      { key: "shopName", value: "Nagraj Mart", description: "Shop name se", disabled: true },
    ]),
    desc: describe({
      tag: TAG.NEW,
      summary: "Vendors ki paginated list — admin panel ki main screen.",
      auth: AUTH_ADMIN,
      when: ["Vendors screen."],
      notes: [
        "**`?zipcode=577001`** sabse kaam ka filter hai — customer complaint aaye to turant pata chalta hai kaunsa vendor us area ka hai.",
        "`limit` max 100.",
        "Stage pe abhi ek hi vendor hai — Nagraj Mart.",
      ],
      enums: [["status", "`APPROVED` · `SUSPENDED`", "Vendor ka state"]],
      errors: [["403", "—", "Admin nahi ho"], E.UNAUTH],
    }),
    script: [
      "const j = pm.response.json();",
      "const list = (j && j.data && j.data.data) || [];",
      "if (list.length) {",
      '    pm.environment.set("vendorId", list[0].userId || list[0]._id);',
      "}",
      "",
      'pm.test("200 OK", () => pm.response.to.have.status(200));',
    ],
  },

  {
    id: "adm.vendor.get",
    group: "02 Vendor Management",
    name: "04 · 🆕 Vendor ki full detail",
    method: "GET",
    path: "/vendors/get/{{vendorId}}",
    auth: "adminToken",
    tag: TAG.NEW,
    desc: describe({
      tag: TAG.NEW,
      summary: "Ek vendor ki poori detail — profile, delivery config, branches aur service areas.",
      auth: AUTH_ADMIN,
      when: ["Vendor list se kisi vendor pe click karne pe."],
      notes: [
        "Vendor bhi yahi endpoint call karta hai par sirf **apni** id ke liye; doosri id pe `403 FORBIDDEN`. Admin kisi ki bhi dekh sakta hai.",
        "`serviceAreas[]` se dikh jata hai vendor kaunse pincodes cover karta hai.",
        "`defaultLocationId` = wo branch jisse distance naapi jati hai.",
      ],
      errors: [E.NOT_FOUND, E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  {
    id: "adm.vendor.update",
    group: "02 Vendor Management",
    name: "05 · 🆕 Vendor detail update",
    method: "PUT",
    path: "/vendors/update/{{vendorId}}",
    auth: "adminToken",
    tag: TAG.NEW,
    body: {
      type: "json",
      value: {
        shopName: "Nagraj Mart",
        name: "Nagraj",
        mobile: "8210574144",
        legalName: "Nagraj Traders",
        gstNumber: "29ABCDE1234F1Z5",
        fssaiNumber: "11223344556677",
        supportMobile: "8210574144",
        commissionPercent: 5,
        payout: {
          accountHolder: "Nagraj",
          accountNumber: "1234567890123",
          ifsc: "SBIN0001234",
          upiId: "nagraj@okaxis",
        },
      },
    },
    desc: describe({
      tag: TAG.NEW,
      summary: "Vendor ki shop details, commission aur payout admin update karta hai.",
      auth: AUTH_ADMIN,
      when: ["Vendor detail screen → Edit."],
      notes: [
        "**Shop name, mobile, GST, payout — sab admin ke haath me hai.** Vendor apne panel se ye nahi badal sakta; wo sirf `PUT /vendors/me/delivery` (delivery config) badal sakta hai.",
        "Admin yahan `delivery` bhi bhej sakta hai — vendor ki setting override karne ke liye. Fields wahi hain jo vendor ke endpoint pe hain.",
        "`email` yahan se nahi badal sakta (login identity hai).",
        "Kam se kam **1 field** zaroori.",
      ],
      fields: [
        ["shopName", "string", "no", "`Nagraj Mart`"],
        ["name", "string", "no", "`Nagraj`"],
        ["mobile", "string", "no", "`8210574144`"],
        ["legalName / gstNumber / fssaiNumber / supportMobile / logo", "string", "no", "Shop ki details"],
        ["commissionPercent", "number", "no", "`5` — 0 se 100"],
        ["status", "enum", "no", "`APPROVED` · `SUSPENDED`"],
        ["delivery", "object", "no", "Vendor ki delivery config override"],
        ["payout", "object", "no", "`accountHolder`, `accountNumber`, `ifsc`, `upiId`"],
      ],
      enums: [["status", "`APPROVED` · `SUSPENDED`", "Yahan se bhi set ho sakta hai"]],
      errors: [["422", "—", "Ek bhi field nahi bheji"], E.NOT_FOUND, E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  {
    id: "adm.vendor.status",
    group: "02 Vendor Management",
    name: "06 · 🆕 Vendor suspend / approve",
    method: "PUT",
    path: "/vendors/status/{{vendorId}}",
    auth: "adminToken",
    tag: TAG.NEW,
    body: { type: "json", value: { status: "SUSPENDED" } },
    desc: describe({
      tag: TAG.NEW,
      summary: "Vendor ko suspend ya wapas approve karta hai.",
      auth: AUTH_ADMIN,
      when: ["Vendor rule tode ya temporarily band karna ho."],
      notes: [
        "**`SUSPENDED` karte hi us vendor ke pincode wale customers ko catalog dikhna band ho jata hai** — unhe `404 PINCODE_NOT_SERVICEABLE` milne lagega. Panel me confirm dialog zaroor rakho.",
        "Uske chal rahe orders khatam nahi hote — vendor unhe aage badha sakta hai.",
        "`APPROVED` karne pe sab wapas normal.",
      ],
      fields: [["status", "enum", "yes", "`APPROVED` ya `SUSPENDED`"]],
      enums: [["status", "`APPROVED` · `SUSPENDED`", "Sirf ye do"]],
      errors: [E.VALIDATION, E.NOT_FOUND, E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  // ══════════════════════════════════════════════════════════════
  {
    id: "adm.branch.create",
    group: "03 Branches",
    name: "07 · 🆕 Nayi branch add karo",
    method: "POST",
    path: "/vendors/{{vendorId}}/branches",
    auth: "adminToken",
    tag: TAG.NEW,
    body: {
      type: "json",
      value: {
        name: "Shivaji Nagar Branch",
        shopOrBuildingNumber: "8",
        address: "8, Shivaji Nagar Main Road",
        area: "Shivaji Nagar",
        city: "Davangere",
        district: "Davangere",
        state: "Karnataka",
        country: "India",
        zipcode: "577002",
        coordinates: [14.4712, 75.9105],
        isDefault: false,
      },
    },
    desc: describe({
      tag: TAG.NEW,
      summary: "Vendor ki extra branch (godown / dukaan) add karta hai.",
      auth: AUTH_ADMIN,
      when: ["Vendor ke ek se zyada outlets ho."],
      notes: [
        "**Branch sirf admin bana sakta hai** — vendor ko sirf read access hai.",
        "Multiple branches allowed hain, **par delivery distance hamesha `isDefault: true` wali branch se hi naapi jati hai**. Doosri branches abhi sirf record/pickup ke liye hain.",
        "`isDefault: true` bhejoge to purani default apne aap hat jayegi.",
        "`coordinates` **[latitude, longitude]** — galat order me delivery charge galat aayega.",
        "Service area assign karte waqt ye `locationId` chahiye hota hai.",
      ],
      fields: BRANCH_FIELDS,
      errors: [E.VALIDATION, E.NOT_FOUND, E.UNAUTH],
    }),
    script: saveId("branchId", "data", 201),
  },

  {
    id: "adm.branch.getAll",
    group: "03 Branches",
    name: "08 · 🆕 Vendor ki branches",
    method: "GET",
    path: "/vendors/{{vendorId}}/branches",
    auth: "adminToken",
    tag: TAG.NEW,
    desc: describe({
      tag: TAG.NEW,
      summary: "Ek vendor ki saari branches.",
      auth: AUTH_ADMIN,
      when: ["Service area assign karne se pehle — `locationId` yahin se milega."],
      notes: [
        "Vendor bhi ye call kar sakta hai (apni hi id pe) — usko read-only dikhani hai.",
        "`isDefault: true` wali branch highlight karo.",
      ],
      errors: [E.NOT_FOUND, E.UNAUTH],
    }),
    script: [
      "const j = pm.response.json();",
      "const list = (j && j.data && (j.data.data || j.data)) || [];",
      "const def = Array.isArray(list) ? (list.find(b => b.isDefault) || list[0]) : null;",
      'if (def) pm.environment.set("branchId", def._id);',
      "",
      'pm.test("200 OK", () => pm.response.to.have.status(200));',
    ],
  },

  {
    id: "adm.branch.setDefault",
    group: "03 Branches",
    name: "09 · 🆕 Default branch badlo",
    method: "PUT",
    path: "/vendors/{{vendorId}}/branches/{{branchId}}/default",
    auth: "adminToken",
    tag: TAG.NEW,
    desc: describe({
      tag: TAG.NEW,
      summary: "Kis branch se delivery distance naapi jaye — wo set karta hai. Body ki zaroorat nahi.",
      auth: AUTH_ADMIN,
      when: ["Vendor apni main shop shift kare.", "Default branch galti se delete ho gayi ho."],
      notes: [
        "**Ye seedha delivery charge pe asar karta hai** — distance isi branch se naapi jati hai.",
        "Default branch kabhi delete nahi ho sakti (pehle doosri ko default banao). Pehle ye guard nahi tha — default branch delete karne pe har order `503 VENDOR_PICKUP_MISSING` dene lagta tha.",
        "`profile.defaultLocationId` bhi saath me update ho jata hai.",
      ],
      errors: [E.NOT_FOUND, E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  // ══════════════════════════════════════════════════════════════
  {
    id: "adm.area.lookup",
    group: "04 Service Areas (pincode)",
    name: "10 · 🆕 ⭐ Pincode kiska hai (assign se PEHLE)",
    method: "GET",
    path: "/service-areas/lookup",
    auth: "adminToken",
    tag: TAG.NEW,
    query: [
      { key: "zipcode", value: "577001", description: "6 digit PIN — required" },
    ],
    desc: describe({
      tag: TAG.NEW,
      summary: "Batata hai ye pincode kisi vendor ko assign hai ya free hai.",
      auth: AUTH_ADMIN,
      when: [
        "**Service area assign karne se hamesha pehle** — warna `409 PINCODE_ALREADY_ASSIGNED` khayenge.",
        "Customer complain kare 'mere area me delivery nahi' to bhi.",
      ],
      notes: [
        "Hamesha `200` deta hai — `assigned: true/false` se pata chalta hai.",
        "`assigned: true` pe `vendor` object me kiska hai wo aata hai.",
        "**Ek pincode = ek hi vendor** (exclusive territory rule). Kisi doosre ko dena ho to `PUT /service-areas/reassign`.",
      ],
      query: [["zipcode", "`577001` — required"]],
      errors: [["422", "—", "`zipcode` missing"], E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  {
    id: "adm.area.create",
    group: "04 Service Areas (pincode)",
    name: "11 · 🆕 ⭐ Pincode assign karo (yahi se customers ko dikhta hai)",
    method: "POST",
    path: "/vendors/{{vendorId}}/service-areas",
    auth: "adminToken",
    tag: TAG.NEW,
    body: {
      type: "json",
      value: {
        locationId: "{{branchId}}",
        areas: [
          {
            zipcode: "577001",
            city: "Davangere",
            district: "Davangere",
            state: "Karnataka",
            country: "India",
            etaMinutes: 60,
            minOrderAmount: 199,
            freeDeliveryAbove: 499,
          },
          {
            zipcode: "577002",
            city: "Davangere",
            district: "Davangere",
            state: "Karnataka",
            etaMinutes: 90,
          },
        ],
      },
    },
    desc: describe({
      tag: TAG.NEW,
      summary:
        "Vendor ko ek ya zyada pincode assign karta hai. **Yahi wo step hai jiske baad customers ko vendor ka catalog dikhna shuru hota hai.**",
      auth: AUTH_ADMIN,
      when: ["Onboarding ka aakhri step — branch ban jane ke baad."],
      notes: [
        "`locationId` **required** hai — batana padta hai kaunsi branch ye area serve karegi. Isliye branch pehle banani padti hai.",
        "`areas` array bhi chalega aur single object bhi.",
        "**`409 PINCODE_ALREADY_ASSIGNED`** — ye platform ka sabse important rule hai. Ek pincode do vendors ko nahi de sakte. Response me purane vendor ka `shopName` aata hai, panel me wahi message dikhao: *\"577001 pehle se Nagraj Mart ko assign hai.\"* Transfer karna ho to `PUT /service-areas/reassign`.",
        "Ye rule DB level pe bhi lagta hai (unique partial index) — race condition me bhi double assign nahi ho sakta.",
        "Per-area optional overrides: `etaMinutes` (app me 'X min me delivery'), `minOrderAmount`, `freeDeliveryAbove`, `deliveryChargeOverride`.",
        "Response me `created` count aur banaye gaye `areas[]` aate hain.",
      ],
      fields: [
        ["locationId", "ObjectId", "**yes**", "`{{branchId}}` — kaunsi branch serve karegi"],
        ["areas", "object[] \\| object", "**yes**", "Neeche wali table"],
      ],
      errors: [
        E.PINCODE_ALREADY_ASSIGNED,
        E.VALIDATION,
        ["404", "—", "Vendor ya branch nahi mili"],
      ],
      extra: [
        "### `areas[]` ka har item",
        "",
        "| Field | Type | Required | Matlab / sample |",
        "|---|---|---|---|",
        "| zipcode | string | **yes** | `577001` |",
        "| city | string | no | `Davangere` |",
        "| district | string | no | `Davangere` |",
        "| state | string | no | `Karnataka` |",
        "| country | string | no | `India` |",
        "| etaMinutes | number | no | `60` — app me delivery time dikhane ke liye |",
        "| minOrderAmount | number | no | `199` — is area ke liye alag minimum |",
        "| freeDeliveryAbove | number | no | `499` — is area me itne upar free |",
        "| deliveryChargeOverride | number | no | Fix charge — vendor ki calculation ko bypass karta hai |",
      ].join("\n"),
    }),
    script: [
      "const j = pm.response.json();",
      "const areas = (j && j.data && j.data.areas) || [];",
      'if (areas.length) pm.environment.set("serviceAreaId", areas[0]._id);',
      "",
      'pm.test("201 Created", () => pm.response.to.have.status(201));',
    ],
  },

  {
    id: "adm.area.getAll",
    group: "04 Service Areas (pincode)",
    name: "12 · 🆕 Vendor ke service areas",
    method: "GET",
    path: "/vendors/{{vendorId}}/service-areas",
    auth: "adminToken",
    tag: TAG.NEW,
    query: [
      { key: "zipcode", value: "577001", description: "Ek pincode dhoondho", disabled: true },
      { key: "isActive", value: "true", description: "Sirf active", disabled: true },
      { key: "page", value: "1", description: "Page", disabled: true },
      { key: "limit", value: "100", description: "Max 500", disabled: true },
    ],
    desc: describe({
      tag: TAG.NEW,
      summary: "Ek vendor ke saare assigned pincodes.",
      auth: AUTH_ADMIN,
      when: ["Vendor detail screen ka 'Coverage' tab."],
      notes: ["Vendor ko bhi yahi list read-only dikhti hai."],
      errors: [E.NOT_FOUND, E.UNAUTH],
    }),
    script: saveFirstId("serviceAreaId", "data.data"),
  },

  {
    id: "adm.area.reassign",
    group: "04 Service Areas (pincode)",
    name: "13 · 🆕 Pincode doosre vendor ko transfer karo",
    method: "PUT",
    path: "/service-areas/reassign",
    auth: "adminToken",
    tag: TAG.NEW,
    body: {
      type: "json",
      value: {
        zipcode: "577001",
        toVendorId: "{{vendorId}}",
        toLocationId: "{{branchId}}",
      },
    },
    desc: describe({
      tag: TAG.NEW,
      summary:
        "Ek pincode ek vendor se le kar doosre ko de deta hai — atomically, ek hi call me.",
      auth: AUTH_ADMIN,
      when: [
        "**`409 PINCODE_ALREADY_ASSIGNED` ka official fix.**",
        "Vendor band ho jaye aur uska area doosre ko dena ho.",
      ],
      notes: [
        "Purana area deactivate/delete hota hai aur naya banta hai — beech me pincode kabhi unassigned nahi rehta.",
        "**⚠️ Asar turant hota hai:** us pincode ke customers ko agli hi request pe naye vendor ka catalog dikhega. Unke cart me purane vendor ke items honge to `409 CART_VENDOR_CONFLICT` milega — app usse handle karti hai.",
        "Purane vendor ke chal rahe orders waise hi rehte hain — wo unhe deliver karega.",
        "`toLocationId` naye vendor ki hi branch honi chahiye.",
      ],
      fields: [
        ["zipcode", "string", "yes", "`577001` — jo transfer karna hai"],
        ["toVendorId", "ObjectId", "yes", "Naya vendor"],
        ["toLocationId", "ObjectId", "yes", "Naye vendor ki branch"],
      ],
      errors: [E.VALIDATION, ["404", "—", "Pincode, vendor ya branch nahi mili"]],
    }),
    script: expectStatus(200),
  },

  {
    id: "adm.area.delete",
    group: "04 Service Areas (pincode)",
    name: "14 · 🆕 Service area hatao",
    method: "DELETE",
    path: "/vendors/{{vendorId}}/service-areas/{{serviceAreaId}}",
    auth: "adminToken",
    tag: TAG.NEW,
    desc: describe({
      tag: TAG.NEW,
      summary: "Vendor se ek pincode hata deta hai (soft delete). Pincode free ho jata hai.",
      auth: AUTH_ADMIN,
      when: ["Vendor ne area cover karna band kar diya."],
      notes: [
        "**⚠️ Hatate hi us pincode ke customers ko `404 PINCODE_NOT_SERVICEABLE` milne lagega.** Doosra vendor dena ho to `reassign` behtar hai — usme gap nahi aata.",
        "Soft delete hai, par unique index sirf `isDeleted: false` pe lagta hai — isliye pincode turant dobara assign ho sakta hai.",
      ],
      errors: [E.NOT_FOUND, E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  // ══════════════════════════════════════════════════════════════
  {
    id: "adm.order.summary",
    group: "05 Orders (sirf dekhna)",
    name: "15 · 🆕 Platform summary",
    method: "GET",
    path: "/orders/admin/summary",
    auth: "adminToken",
    tag: TAG.NEW,
    desc: describe({
      tag: TAG.NEW,
      summary: "Poore platform ke totals + har vendor ka breakdown.",
      auth: AUTH_ADMIN,
      when: ["Admin dashboard ka main data."],
      notes: [
        "`totals` = platform level, `vendors[]` = har vendor ka orders/revenue.",
        "Stage pe abhi ek hi vendor (Nagraj Mart) hai, isliye `vendors[]` me ek hi row aayegi.",
      ],
      errors: [E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  {
    id: "adm.order.getAll",
    group: "05 Orders (sirf dekhna)",
    name: "16 · Saare orders (har vendor ke)",
    method: "GET",
    path: "/orders/getAll",
    auth: "adminToken",
    tag: TAG.CHANGED,
    query: paging([
      { key: "vendorId", value: "{{vendorId}}", description: "🆕 Vendor se filter", disabled: true },
      { key: "userId", value: "{{customerId}}", description: "Customer se filter", disabled: true },
      { key: "status", value: "PENDING", description: "Status se", disabled: true },
      { key: "deliveryPincode", value: "577001", description: "Pincode se", disabled: true },
      { key: "orderNumber", value: "NVS-2609-000004", description: "Exact order", disabled: true },
      { key: "fromDate", value: "2026-09-01", description: "ISO date", disabled: true },
      { key: "toDate", value: "2026-09-30", description: "ISO date", disabled: true },
    ]),
    desc: describe({
      tag: TAG.CHANGED,
      summary: "Saare orders — admin ko platform bhar ke dikhte hain.",
      auth: AUTH_ADMIN,
      when: ["Orders screen, support queries."],
      notes: [
        "**🆕 `?vendorId=` filter** naya hai — kisi ek vendor ke orders dekhne ke liye.",
        "**Removed:** `items[].vendorId` aur `items[].locationId` fields; ab vendor order level pe hai (`order.vendorId`).",
        "Har item me `productSnapshot` hai.",
      ],
      errors: [E.UNAUTH],
    }),
    script: saveFirstId("orderId", "data.data"),
  },

  {
    id: "adm.order.get",
    group: "05 Orders (sirf dekhna)",
    name: "17 · Order detail (read-only)",
    method: "GET",
    path: "/orders/get/{{orderId}}",
    auth: "adminToken",
    tag: TAG.CHANGED,
    desc: describe({
      tag: TAG.CHANGED,
      summary: "Kisi bhi order ki poori detail.",
      auth: AUTH_ADMIN,
      notes: [
        "**⚠️ Admin order ka status badal NAHI sakta.** Purana `PUT /orders/update/:id` (jo admin-only tha) **hata diya gaya hai**. State machine me admin ka column poora khaali hai — ye locked decision (D6) hai.",
        "Order atka hua ho (vendor ne kuch nahi kiya) to admin ko vendor ko call karna padega. Panel me order ke saath vendor ka `supportMobile` dikhao — wahi practical fix hai.",
        "Admin panel me status change ke buttons mat banao — 409 bhi nahi milega, route hi nahi hai (404 Invalid API).",
      ],
      errors: [E.NOT_FOUND, E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  // ══════════════════════════════════════════════════════════════
  {
    id: "adm.user.getAll",
    group: "06 Users",
    name: "18 · 🔒 Saare users",
    method: "GET",
    path: "/users/getAll",
    auth: "adminToken",
    tag: TAG.LOCKED,
    query: paging([
      { key: "role", value: "user", description: "`user` | `vendor` | `admin` | `staff`", disabled: true },
      { key: "isActive", value: "true", description: "Active only", disabled: true },
      { key: "mobile", value: "9886061450", description: "Mobile se dhoondho", disabled: true },
      { key: "email", value: "ramesh.kulkarni@gmail.com", description: "Email se", disabled: true },
    ]),
    desc: describe({
      tag: TAG.LOCKED,
      summary: "Platform ke saare users — customers, vendors, admins.",
      auth: AUTH_ADMIN,
      when: ["Users screen, support lookup."],
      notes: [
        "**🔒 Security fix:** pehle is endpoint pe sirf `verifyJwtToken` tha — koi bhi logged-in **customer** poori user list (1453 users ke email aur mobile) nikal sakta tha. Ab `isAdmin` lagta hai.",
        "`?role=vendor` se saare vendors ki user entries mil jati hain.",
        "`sortBy` valid values: `createdAt`, `name`, `email`, `lastActivity`.",
        "Stage prod ka clone hai, isliye yahan ~1450 asli customers hain.",
      ],
      enums: [
        ["role", "`user` · `vendor` · `admin` · `staff`", "User ka role"],
        ["sortBy", "`createdAt` · `name` · `email` · `lastActivity`", "Isse bahar kuch = 422"],
      ],
      errors: [["403", "—", "Admin nahi ho"], E.UNAUTH],
    }),
    script: saveFirstId("someUserId", "data.data"),
  },

  {
    id: "adm.user.get",
    group: "06 Users",
    name: "19 · 🔒 Kisi user ki profile",
    method: "GET",
    path: "/users/get",
    auth: "adminToken",
    tag: TAG.LOCKED,
    query: [
      { key: "userId", value: "{{someUserId}}", description: "Jiski profile dekhni hai" },
    ],
    desc: describe({
      tag: TAG.LOCKED,
      summary: "Kisi bhi user ki profile (support ke liye).",
      auth: AUTH_ADMIN,
      notes: [
        "**🔒 Security fix (IDOR):** pehle koi bhi customer `?userId=` me kisi aur ka id daal ke uski poori profile padh leta tha. Ab `?userId=` **sirf admin** bhej sakta hai; customer bhejega to apni hi profile milegi.",
        "`?userId=` na do to apni (admin ki) profile aayegi.",
      ],
      query: [["userId", "Target user ka `_id` — sirf admin bhej sakta hai"]],
      errors: [E.NOT_FOUND, E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  {
    id: "adm.user.locations",
    group: "06 Users",
    name: "20 · 🔒 Kisi user ke addresses",
    method: "GET",
    path: "/locations/getAll",
    auth: "adminToken",
    tag: TAG.LOCKED,
    query: paging([
      { key: "userId", value: "{{someUserId}}", description: "Sirf admin bhej sakta hai" },
      { key: "zipcode", value: "577001", description: "Pincode se", disabled: true },
    ]),
    desc: describe({
      tag: TAG.LOCKED,
      summary: "Kisi customer ke saved addresses (delivery issue debug karne ke liye).",
      auth: AUTH_ADMIN,
      notes: [
        "**🔒 Security fix:** pehle ye endpoint har user ko **sabke** addresses de deta tha. Ab customer ko sirf apne milte hain; `?userId=` sirf admin ke liye kaam karta hai.",
        "Customer ka `isDefault: true` wala address hi uska catalog decide karta hai — 'mujhe products nahi dikh rahe' wali complaint yahin se debug hoti hai.",
        "**Note:** stage/prod pe ~93% customers ke paas **koi address nahi** hai — unhe `400 PINCODE_REQUIRED` milega jab tak app onboarding me address na maange.",
      ],
      errors: [E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  // ══════════════════════════════════════════════════════════════
  {
    id: "adm.setting.get",
    group: "07 Platform Settings",
    name: "21 · 🔒 Global settings",
    method: "GET",
    path: "/settings/get",
    auth: "adminToken",
    tag: TAG.LOCKED,
    desc: describe({
      tag: TAG.LOCKED,
      summary: "Platform ke global safety limits.",
      auth: AUTH_ADMIN,
      when: ["Admin → Settings screen."],
      notes: [
        "**🔒 Security fix:** pehle ye sirf `verifyJwtToken` pe tha — koi bhi customer platform settings padh leta tha. Ab `isAdmin`.",
        "**Breaking:** `Setting.delivery` ke **9 purane charge fields hata diye gaye** (`baseCharge`, `perKmRate`, `perKgRate`, `minDeliveryCharge`, `baseMaxCharge`, `maxPerKgIncrement`, `maxPerKmIncrement`, `distanceFactor`, `weightFactor`) aur `shopLocationId` bhi. Delivery charge ab **per-vendor** hai (`PUT /vendors/me/delivery`).",
        "Ab yahan sirf 2 platform-level hard caps bachi hain — ye vendor ki setting ke **upar** lagti hain, vendor inse aage nahi ja sakta.",
      ],
      fields: [
        ["delivery.maxRadiusKm", "number", "—", "`50` — koi vendor isse zyada radius nahi rakh sakta"],
        [
          "delivery.maxAllowedDeliveryCharge",
          "number",
          "—",
          "`200` — kisi bhi order pe delivery charge ki maximum limit",
        ],
      ],
      errors: [["403", "—", "Admin nahi ho"], E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  {
    id: "adm.setting.update",
    group: "07 Platform Settings",
    name: "22 · Global settings update",
    method: "PUT",
    path: "/settings/update",
    auth: "adminToken",
    tag: TAG.CHANGED,
    body: {
      type: "json",
      value: { delivery: { maxRadiusKm: 50, maxAllowedDeliveryCharge: 200 } },
    },
    desc: describe({
      tag: TAG.CHANGED,
      summary: "Platform ke hard caps badalta hai.",
      auth: AUTH_ADMIN,
      notes: [
        "**Breaking:** ab sirf `delivery.maxRadiusKm` aur `delivery.maxAllowedDeliveryCharge` accept hote hain. Purane 9 charge fields bhejoge to chup-chaap strip ho jayenge (`stripUnknown`).",
        "**Ye har vendor pe turant lagta hai** — `maxAllowedDeliveryCharge` ghata doge to saare vendors ka charge us cap pe aa jayega.",
        "Yahan se vendor ki setting nahi badalti — wo har vendor apne panel se karta hai.",
      ],
      fields: [
        ["delivery.maxRadiusKm", "number", "no", "`50`"],
        ["delivery.maxAllowedDeliveryCharge", "number", "no", "`200`"],
      ],
      errors: [E.VALIDATION, E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  {
    id: "adm.setting.create",
    group: "07 Platform Settings",
    name: "23 · Settings pehli baar banao",
    method: "POST",
    path: "/settings/create",
    auth: "adminToken",
    tag: TAG.CHANGED,
    body: {
      type: "json",
      value: { delivery: { maxRadiusKm: 50, maxAllowedDeliveryCharge: 200 } },
    },
    desc: describe({
      tag: TAG.CHANGED,
      summary: "Settings document banata hai (ek hi baar — fresh install pe).",
      auth: AUTH_ADMIN,
      notes: [
        "Settings pehle se hain to `PUT /settings/update` use karo.",
        "Fields wahi do jo update me hain — baaki purane delivery fields hata diye gaye hain.",
      ],
      fields: [
        ["delivery.maxRadiusKm", "number", "no", "`50`"],
        ["delivery.maxAllowedDeliveryCharge", "number", "no", "`200`"],
      ],
      errors: [E.VALIDATION, E.UNAUTH],
    }),
    script: expectStatus(201),
  },

  // ══════════════════════════════════════════════════════════════
  {
    id: "adm.banner.create",
    group: "08 Content",
    name: "24 · Banner banao",
    method: "POST",
    path: "/banners/create",
    auth: "adminToken",
    tag: TAG.SAME,
    body: {
      type: "formdata",
      fields: [
        { key: "name", value: "Monsoon Rice Offer", type: "text", description: "3–120 chars, required" },
        { key: "description", value: "Basmati pe 10% off — is hafte tak", type: "text", description: "max 300" },
        { key: "isActive", value: "true", type: "text", description: "`true` | `false`" },
        { key: "image", value: "", type: "file", description: "Banner image — image YA video me se ek ZARURI hai" },
        { key: "video", value: "", type: "file", description: "Banner video — image ke badle ye bhej sakte ho" },
      ],
    },
    desc: describe({
      tag: TAG.SAME,
      summary: "Home screen ka promotional banner banata hai.",
      auth: AUTH_ADMIN,
      notes: [
        "`multipart/form-data` hai. **`image` ya `video` me se ek bhejna ZARURI hai** — dono chhod diye to `422 Either video or image is required`.",
        "Banners **global** hain — sab customers ko dikhte hain, vendor-scoped nahi. Koi vendor apna banner nahi bana sakta.",
      ],
      fields: [
        ["name", "string", "yes", "`Monsoon Rice Offer`"],
        ["description", "string", "no", "max 300"],
        ["isActive", "boolean", "no", "default `true`"],
        ["image", "file", "image ya video", "jpg/png"],
        ["video", "file", "image ya video", "mp4"],
      ],
      errors: [
        ["422", "—", "`Either video or image is required` — dono khaali chhod diye"],
        E.VALIDATION,
        E.UNAUTH,
      ],
    }),
    script: saveId("bannerId", "data", 201),
  },

  {
    id: "adm.banner.delete",
    group: "08 Content",
    name: "25 · Banner delete",
    method: "DELETE",
    path: "/banners/delete/{{bannerId}}",
    auth: "adminToken",
    tag: TAG.SAME,
    desc: describe({
      tag: TAG.SAME,
      summary: "Banner soft-delete karta hai.",
      auth: AUTH_ADMIN,
      errors: [E.NOT_FOUND, E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  {
    id: "adm.terms.create",
    group: "08 Content",
    name: "26 · Terms banao",
    method: "POST",
    path: "/terms-and-conditions/create",
    auth: "adminToken",
    tag: TAG.SAME,
    body: {
      type: "json",
      value: {
        title: "Order aur Delivery",
        description:
          "Order confirm hone ke baad vendor use accept karta hai. Delivery time aapke area ke hisaab se badal sakta hai.",
        isActive: true,
      },
    },
    desc: describe({
      tag: TAG.SAME,
      summary: "Terms & Conditions ki ek entry banata hai.",
      auth: AUTH_ADMIN,
      fields: [
        ["title", "string", "yes", "`Order aur Delivery` — 3 se 120 chars"],
        ["description", "string", "no", "max 300 chars"],
        ["isActive", "boolean", "no", "default `true`"],
      ],
      errors: [E.VALIDATION, E.UNAUTH],
    }),
    script: saveId("termId", "data", 201),
  },

  {
    id: "adm.terms.update",
    group: "08 Content",
    name: "27 · Terms update",
    method: "PUT",
    path: "/terms-and-conditions/update/{{termId}}",
    auth: "adminToken",
    tag: TAG.SAME,
    body: {
      type: "json",
      value: {
        title: "Order aur Delivery",
        description:
          "Order confirm hone ke baad vendor use accept karta hai. PACKED hone ke baad cancel nahi ho sakta.",
        isActive: true,
      },
    },
    desc: describe({
      tag: TAG.SAME,
      summary: "Terms entry edit karta hai.",
      auth: AUTH_ADMIN,
      notes: [
        "**⚠️ Ye endpoint pehle poora tuta hua tha** — `title` bhejne pe hamesha `500` aata tha (`result.findOne is not a function`), aur `isActive` bhejne pe value **ulti** ho jati thi (toggle). Dono fix ho gaye hain: ab `isActive` **set** hota hai aur duplicate title pe saaf `409` milta hai.",
        "Panel se `isActive` ki nayi value bhejo, purana \"bas field bhej do\" wala code hata do.",
        "🔤 `title` **Title Case** me aur `description` **sentence case** me save hote hain (pehle dono lowercase ho jate the). Duplicate check case-insensitive hai — \"Refund Policy\" aur \"refund policy\" ek hi maane jayenge.",
      ],
      fields: [
        ["title", "string", "no", "3 se 120 chars"],
        ["description", "string", "no", "max 300"],
        ["isActive", "boolean", "no", "`true`/`false` — **set**, toggle nahi"],
      ],
      errors: [
        ["409", "—", "Isi title se doosri entry pehle se hai"],
        E.NOT_FOUND,
        E.VALIDATION,
        E.UNAUTH,
      ],
    }),
    script: expectStatus(200),
  },

  {
    id: "adm.terms.delete",
    group: "08 Content",
    name: "28 · Terms delete",
    method: "DELETE",
    path: "/terms-and-conditions/delete/{{termId}}",
    auth: "adminToken",
    tag: TAG.SAME,
    desc: describe({
      tag: TAG.SAME,
      summary: "Terms entry soft-delete karta hai.",
      auth: AUTH_ADMIN,
      errors: [E.NOT_FOUND, E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  {
    id: "adm.privacy.create",
    group: "08 Content",
    name: "29 · Privacy policy banao",
    method: "POST",
    path: "/privacy-and-policies/create",
    auth: "adminToken",
    tag: TAG.SAME,
    body: {
      type: "json",
      value: {
        title: "Aapka data",
        description:
          "Hum aapka naam, mobile aur delivery address sirf order pura karne ke liye use karte hain.",
        isActive: true,
      },
    },
    desc: describe({
      tag: TAG.SAME,
      summary: "Privacy policy ki ek entry banata hai.",
      auth: AUTH_ADMIN,
      fields: [
        ["title", "string", "yes", "`Aapka data` — 3 se 120 chars"],
        ["description", "string", "no", "max 300 chars"],
        ["isActive", "boolean", "no", "default `true`"],
      ],
      errors: [E.VALIDATION, E.UNAUTH],
    }),
    script: saveId("privacyId", "data", 201),
  },

  {
    id: "adm.privacy.update",
    group: "08 Content",
    name: "30 · Privacy policy update",
    method: "PUT",
    path: "/privacy-and-policies/update/{{privacyId}}",
    auth: "adminToken",
    tag: TAG.SAME,
    body: {
      type: "json",
      value: {
        title: "Aapka data",
        description:
          "Hum aapka naam, mobile aur delivery address sirf order pura karne ke liye use karte hain. Kisi third party ko nahi dete.",
        isActive: true,
      },
    },
    desc: describe({
      tag: TAG.SAME,
      summary: "Privacy policy entry edit karta hai.",
      auth: AUTH_ADMIN,
      notes: [
        "**⚠️ Ye endpoint pehle poora tuta hua tha** — `title` bhejne pe hamesha `500` aata tha (`result.findOne is not a function`), aur `isActive` bhejne pe value **ulti** ho jati thi (toggle). Dono fix ho gaye hain: ab `isActive` **set** hota hai aur duplicate title pe saaf `409` milta hai.",
        "Panel se `isActive` ki nayi value bhejo, purana \"bas field bhej do\" wala code hata do.",
        "🔤 `title` **Title Case** me aur `description` **sentence case** me save hote hain (pehle dono lowercase ho jate the). Duplicate check case-insensitive hai — \"Refund Policy\" aur \"refund policy\" ek hi maane jayenge.",
      ],
      fields: [
        ["title", "string", "no", "3 se 120 chars"],
        ["description", "string", "no", "max 300"],
        ["isActive", "boolean", "no", "`true`/`false` — **set**, toggle nahi"],
      ],
      errors: [
        ["409", "—", "Isi title se doosri entry pehle se hai"],
        E.NOT_FOUND,
        E.VALIDATION,
        E.UNAUTH,
      ],
    }),
    script: expectStatus(200),
  },

  {
    id: "adm.privacy.delete",
    group: "08 Content",
    name: "31 · Privacy policy delete",
    method: "DELETE",
    path: "/privacy-and-policies/delete/{{privacyId}}",
    auth: "adminToken",
    tag: TAG.SAME,
    desc: describe({
      tag: TAG.SAME,
      summary: "Privacy policy entry soft-delete karta hai.",
      auth: AUTH_ADMIN,
      errors: [E.NOT_FOUND, E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  {
    id: "adm.sub.create",
    group: "08 Content",
    name: "32 · Subscription plan banao",
    method: "POST",
    path: "/subscriptions/add",
    auth: "adminToken",
    tag: TAG.SAME,
    body: {
      type: "json",
      value: {
        name: "Monthly Saver",
        description: "Har mahine free delivery aur priority support",
        price: 199,
        type: "monthly",
        durationInDays: 30,
        benefits: ["Free delivery", "Priority support"],
        limitations: ["Ek hi address pe valid"],
        isActive: true,
      },
    },
    desc: describe({
      tag: TAG.SAME,
      summary: "Subscription plan banata hai.",
      auth: AUTH_ADMIN,
      notes: [
        "Subscription feature abhi customer app me wired nahi hai — plan sirf banaye jaate hain.",
      ],
      fields: [
        ["name", "string", "yes", "`Monthly Saver` — 3 se 120 chars"],
        ["price", "number", "yes", "`199`"],
        ["type", "enum", "yes", "`monthly`"],
        ["description", "string", "no", "max 500 chars"],
        ["durationInDays", "number", "no", "`30`"],
        ["benefits", "string[]", "no", "`[\"Free delivery\", \"Priority support\"]`"],
        ["limitations", "string[]", "no", "`[\"Ek hi address pe valid\"]`"],
        ["isActive", "boolean", "no", "default `true`"],
      ],
      enums: [
        [
          "type",
          "`weekly` · `monthly` · `quarterly` · `half_yearly` · `yearly`",
          "Plan ka duration type",
        ],
      ],
      errors: [E.VALIDATION, E.UNAUTH],
    }),
    script: expectStatus(201),
  },
];
