/**
 * VENDOR (shop panel) — login se lekar order DELIVERED tak.
 */
const {
  TAG,
  E,
  paging,
  describe,
  saveToken,
  saveFirstId,
  saveId,
  expectStatus,
} = require("./shared");

const AUTH_VENDOR = "`Bearer {{vendorToken}}` — role `vendor`";

const DELIVERY_FIELDS = [
  ["isEnabled", "boolean", "no", "**Master switch.** `false` = delivery charge hamesha ₹0. Default `false`"],
  ["baseCharge", "number", "no", "`30` — har order pe fixed"],
  ["perKmRate", "number", "no", "`5` — per km"],
  ["perKgRate", "number", "no", "`1.5` — per kg"],
  ["minDeliveryCharge", "number", "no", "`40` — calculation isse kam aaya to ye lagega"],
  ["baseMaxCharge", "number \\| null", "no", "`150` — total charge ki cap. `null` = koi cap nahi"],
  ["maxPerKgIncrement", "number \\| null", "no", "`1.2` — weight component ki cap"],
  ["maxPerKmIncrement", "number \\| null", "no", "`4` — distance component ki cap"],
  ["freeDeliveryAbove", "number \\| null", "no", "`499` → itne ke upar delivery free. `null` = free delivery nahi"],
  ["minOrderAmount", "number", "no", "`0` — isse kam ka order place hi nahi hoga"],
  ["maxRadiusKm", "number \\| null", "no", "`12` — isse door deliver nahi. `null` = koi limit nahi"],
];

module.exports = [
  // ══════════════════════════════════════════════════════════════
  {
    id: "vend.auth.login",
    group: "01 Auth",
    name: "01 · ⭐ Vendor login",
    method: "POST",
    path: "/auth/login",
    auth: null,
    tag: TAG.SAME,
    body: {
      type: "json",
      value: {
        type: "email",
        email: "nagraj@gmail.com",
        password: "nagraj@123",
        role: "vendor",
        loginType: "password",
      },
    },
    desc: describe({
      tag: TAG.SAME,
      summary: "Vendor panel ka login. Token `{{vendorToken}}` me apne aap save ho jata hai.",
      auth: "Public",
      when: ["Sabse pehla call."],
      notes: [
        "**Vendor ka self-signup nahi hai.** Account admin banata hai (`POST /vendors/create`) aur wahi email/password vendor ko deta hai.",
        "`role: \"vendor\"` bhejna **zaroori** hai — lookup usi se hota hai. Bhoole to customer table me dhoondhega aur `404` dega.",
        "Response ke `data.user._id` hi **vendorId** hai — aage `GET /vendors/get/:id` jaise calls me yahi lagta hai. Test script ise `{{vendorId}}` me save kar deta hai.",
        "**Stage credentials:** `nagraj@gmail.com` / `nagraj@123`",
      ],
      fields: [
        ["type", "enum", "yes", "`email` (ya `mobile`)"],
        ["email", "string", "type=email pe", "`nagraj@gmail.com`"],
        ["mobile", "string", "type=mobile pe", "`8210574144`"],
        ["password", "string", "yes", "`nagraj@123`"],
        ["role", "enum", "yes", "`vendor` — bhoolna nahi"],
        ["loginType", "enum", "no", "default `password`"],
      ],
      enums: [
        ["type", "`email` · `mobile`", "Kis field se lookup karna hai"],
        ["role", "`vendor`", "Vendor panel ke liye hamesha `vendor`"],
      ],
      errors: [
        ["403", "—", "Wrong password"],
        ["404", "—", "Is email + role=vendor ka account nahi hai"],
      ],
    }),
    script: [
      ...saveToken("vendorToken", "vendorId"),
      "",
      "// vendorId = user ka _id (VendorProfile isi se link hoti hai)",
    ],
  },

  // ══════════════════════════════════════════════════════════════
  {
    id: "vend.me.profile",
    group: "02 Profile & Delivery",
    name: "02 · 🆕 Meri vendor profile",
    method: "GET",
    path: "/vendors/get/{{vendorId}}",
    auth: "vendorToken",
    tag: TAG.NEW,
    desc: describe({
      tag: TAG.NEW,
      summary:
        "Vendor ki poori profile — shop details, delivery settings, branches aur service areas ek saath.",
      auth: AUTH_VENDOR,
      when: ["Login ke turant baad — dashboard header aur settings screen ka data."],
      notes: [
        "Vendor sirf **apni** profile padh sakta hai; kisi aur ka id daala to `403 FORBIDDEN`.",
        "`delivery` object ko settings screen pe form me bharo — usi ko `PUT /vendors/me/delivery` se save karna hai.",
        "`branches[]` aur `serviceAreas[]` **read-only** hain vendor ke liye — inhe admin manage karta hai. UI me inhe disabled/read-only dikhao aur 'change ke liye admin se sampark karein' likh do.",
        "`defaultLocationId` batata hai kaunsi branch se distance naapi jaati hai.",
        "`status` `APPROVED` ya `SUSPENDED` hota hai. `SUSPENDED` hone pe vendor ka catalog customers ko dikhna band ho jata hai.",
      ],
      enums: [
        ["status", "`APPROVED` · `SUSPENDED`", "Admin control karta hai"],
        ["branches[].type", "`VENDOR_BRANCH`", "Vendor branch ka location type"],
      ],
      errors: [E.FORBIDDEN, E.NOT_FOUND, E.UNAUTH],
    }),
    script: [
      "const j = pm.response.json();",
      "const d = j && j.data;",
      "if (d) {",
      "    const def = (d.branches || []).find(b => b.isDefault) || (d.branches || [])[0];",
      '    if (def) pm.environment.set("branchId", def._id);',
      "    const area = (d.serviceAreas || [])[0];",
      '    if (area) pm.environment.set("serviceAreaId", area._id);',
      "}",
      "",
      'pm.test("200 OK", () => pm.response.to.have.status(200));',
    ],
  },

  {
    id: "vend.me.delivery",
    group: "02 Profile & Delivery",
    name: "03 · 🆕 ⭐ Delivery settings update (vendor ka ekmatra edit right)",
    method: "PUT",
    path: "/vendors/me/delivery",
    auth: "vendorToken",
    tag: TAG.NEW,
    body: {
      type: "json",
      value: {
        isEnabled: true,
        baseCharge: 30,
        perKmRate: 5,
        perKgRate: 1.5,
        minDeliveryCharge: 40,
        baseMaxCharge: 150,
        maxPerKgIncrement: 1.2,
        maxPerKmIncrement: 4,
        freeDeliveryAbove: 499,
        minOrderAmount: 199,
        maxRadiusKm: 12,
      },
    },
    desc: describe({
      tag: TAG.NEW,
      summary:
        "Vendor apni delivery charge ki setting khud badalta hai. **Panel me vendor sirf yahi edit kar sakta hai.**",
      auth: AUTH_VENDOR,
      when: ["Settings → Delivery screen se, jab bhi vendor rate badle."],
      notes: [
        "**Baaki sab admin ke haath me hai** — shop name, mobile, address, branches, pincode. Vendor sirf delivery config badal sakta hai. Panel me baaki fields read-only rakho.",
        "Kam se kam **1 field** bhejna zaroori hai (`{}` bhejoge to `422`).",
        "**`isEnabled` master switch hai.** `false` (default) = delivery charge hamesha **₹0**, chahe baaki values kuch bhi ho. Panel me sabse upar ek toggle rakho.",
        "Cap fields (`baseMaxCharge`, `maxPerKgIncrement`, `maxPerKmIncrement`, `freeDeliveryAbove`, `maxRadiusKm`) me **`null` ka matlab 'koi limit nahi'** hai, `0` ka matlab 'limit 0' — yaani charge hamesha 0. UI me 'No limit' checkbox se `null` bhejo, khaali input ko `0` mat bhejna.",
        "Platform hard caps: delivery charge max **₹200**, radius max **50 km**. Isse upar bhejoge to server chup-chaap cap laga dega.",
        "Naya vendor by-default: `isEnabled: false` par baaki values bhari hui (`baseCharge 30`, `perKmRate 5`, `perKgRate 1.5`, `minDeliveryCharge 40`) — taaki toggle on karte hi sensible charge lage.",
      ],
      fields: DELIVERY_FIELDS,
      enums: [["isEnabled", "`true` · `false`", "`false` = charge ₹0 (default)"]],
      errors: [
        ["422", "—", "Ek bhi field nahi bheji, ya koi value negative hai"],
        E.UNAUTH,
      ],
      extra: [
        "### Delivery charge kaise banta hai",
        "",
        "```",
        "isEnabled false      →  charge = 0        (bas, aage kuch nahi)",
        "isEnabled true       →",
        "   distancePart = min(distanceKm × perKmRate, maxPerKmIncrement × distanceKm)",
        "   weightPart   = min(totalKg   × perKgRate, maxPerKgIncrement × totalKg)",
        "   charge       = baseCharge + distancePart + weightPart",
        "   charge       = max(charge, minDeliveryCharge)",
        "   charge       = min(charge, baseMaxCharge)          // null ho to skip",
        "   subTotal >= freeDeliveryAbove  →  charge = 0       // null ho to skip",
        "   charge       = min(charge, 200)                    // platform hard cap",
        "```",
        "",
        "Koi hidden code-constant fallback **nahi** hai — jo vendor ne set kiya wahi lagta hai.",
      ].join("\n"),
    }),
    script: expectStatus(200),
  },

  {
    id: "vend.me.branches",
    group: "02 Profile & Delivery",
    name: "04 · 🆕 Meri branches (read-only)",
    method: "GET",
    path: "/vendors/{{vendorId}}/branches",
    auth: "vendorToken",
    tag: TAG.NEW,
    desc: describe({
      tag: TAG.NEW,
      summary: "Vendor ki saari branches. Vendor ke liye ye **sirf padhne** ke liye hai.",
      auth: AUTH_VENDOR,
      when: ["Settings → Shop Locations screen."],
      notes: [
        "Branch add/edit/delete **sirf admin** kar sakta hai. Vendor panel me 'Add branch' button mat rakho — ya rakho to admin se request karne wala flow banao.",
        "`isDefault: true` wali branch se hi customer ka **delivery distance** naapa jata hai — isliye panel me use highlight karo.",
        "`type` hamesha `VENDOR_BRANCH` hota hai.",
      ],
      errors: [E.FORBIDDEN, E.UNAUTH],
    }),
    script: [
      "const j = pm.response.json();",
      "const list = (j && j.data && (j.data.data || j.data)) || [];",
      "const def = Array.isArray(list) ? (list.find(b => b.isDefault) || list[0]) : null;",
      'if (def) pm.environment.set("branchId", def._id);',
      "",
      'pm.test("200 OK", () => pm.response.to.have.status(200));',
    ],
  },

  {
    id: "vend.me.serviceAreas",
    group: "02 Profile & Delivery",
    name: "05 · 🆕 Mere service pincodes (read-only)",
    method: "GET",
    path: "/vendors/{{vendorId}}/service-areas",
    auth: "vendorToken",
    tag: TAG.NEW,
    query: [
      { key: "zipcode", value: "577001", description: "Ek pincode dhoondho", disabled: true },
      { key: "isActive", value: "true", description: "Sirf active areas", disabled: true },
      { key: "page", value: "1", description: "Page", disabled: true },
      { key: "limit", value: "100", description: "Max 500", disabled: true },
    ],
    desc: describe({
      tag: TAG.NEW,
      summary: "Vendor kaunse pincodes pe deliver karta hai — read-only list.",
      auth: AUTH_VENDOR,
      when: ["Settings → Service Areas screen."],
      notes: [
        "Pincode add/remove **sirf admin** karta hai. Vendor ko naya area chahiye to admin se bolna padega.",
        "Ek pincode **sirf ek hi** vendor ka hota hai (exclusive territory) — isliye yahan jo pincodes dikhe, unpe koi doosra vendor nahi hai.",
        "Har area pe optional overrides ho sakte hain: `etaMinutes`, `minOrderAmount`, `freeDeliveryAbove`, `deliveryChargeOverride`.",
      ],
      errors: [E.FORBIDDEN, E.UNAUTH],
    }),
    script: saveFirstId("serviceAreaId", "data.data"),
  },

  // ══════════════════════════════════════════════════════════════
  {
    id: "vend.cat.create",
    group: "03 Catalog · Categories",
    name: "06 · Category banao",
    method: "POST",
    path: "/categories/create",
    auth: "vendorToken",
    tag: TAG.CHANGED,
    body: {
      type: "formdata",
      fields: [
        { key: "name", value: "Rice & Grains", type: "text", description: "3–120 chars, required" },
        { key: "description", value: "Basmati, sona masoori aur doosre chawal", type: "text", description: "max 300 chars" },
        { key: "isActive", value: "true", description: "`true` | `false`", type: "text" },
        { key: "image", value: "", type: "file", description: "Category icon (optional) — na do to default image lagti hai" },
      ],
    },
    desc: describe({
      tag: TAG.CHANGED,
      summary: "Vendor apni category banata hai.",
      auth: AUTH_VENDOR,
      when: ["Catalog setup ka pehla step — product banane se pehle category chahiye."],
      notes: [
        "**`multipart/form-data`** hai kyunki `image` upload hoti hai. Image optional hai — na do to default image lag jati hai (Cloudinary call bhi nahi hoti).",
        "**Change:** `userId` body me mat bhejo — token se apne aap lagta hai. Pehle catalog global tha, ab har category ek vendor ki hoti hai.",
        "Customers ko ye category tabhi dikhegi jab unka pincode is vendor ka ho.",
      ],
      fields: [
        ["name", "string", "yes", "`Rice & Grains` — 3 se 120 chars"],
        ["description", "string", "no", "max 300 chars"],
        ["isActive", "boolean", "no", "default `true`"],
        ["image", "file", "no", "jpg/png"],
      ],
      errors: [E.VALIDATION, E.UNAUTH],
    }),
    script: saveId("categoryId", "data", 201),
  },

  {
    id: "vend.cat.getAll",
    group: "03 Catalog · Categories",
    name: "07 · Meri categories",
    method: "GET",
    path: "/categories/getAll",
    auth: "vendorToken",
    tag: TAG.CHANGED,
    query: paging([
      { key: "isActive", value: "true", description: "Sirf active", disabled: true },
    ]),
    desc: describe({
      tag: TAG.CHANGED,
      summary: "Vendor ki apni categories.",
      auth: AUTH_VENDOR,
      when: ["Catalog screen."],
      notes: [
        "Vendor ko pincode dene ki zaroorat **nahi** — server token se hi uska scope samajh leta hai. `PINCODE_REQUIRED` vendor ko kabhi nahi aata.",
        "Inactive categories bhi dikhti hain taaki panel se toggle kar sako (`?isActive=` se filter kar lo).",
      ],
      errors: [E.UNAUTH],
    }),
    script: saveFirstId("categoryId", "data.data"),
  },

  {
    id: "vend.cat.get",
    group: "03 Catalog · Categories",
    name: "08 · Ek category",
    method: "GET",
    path: "/categories/get/{{categoryId}}",
    auth: "vendorToken",
    tag: TAG.CHANGED,
    desc: describe({
      tag: TAG.CHANGED,
      summary: "Ek category ki detail (edit form bharne ke liye).",
      auth: AUTH_VENDOR,
      notes: ["Doosre vendor ki category ka id → `404`."],
      errors: [E.NOT_FOUND, E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  {
    id: "vend.cat.update",
    group: "03 Catalog · Categories",
    name: "09 · ⚠️ Category update (isActive ab TOGGLE nahi, SET hai)",
    method: "PUT",
    path: "/categories/update/{{categoryId}}",
    auth: "vendorToken",
    tag: TAG.BREAKING,
    body: {
      type: "formdata",
      fields: [
        { key: "name", value: "Rice & Grains", type: "text", description: "3–120 chars" },
        { key: "description", value: "Basmati, sona masoori aur doosre chawal", type: "text", description: "max 300" },
        { key: "isActive", value: "false", type: "text", description: "Jo bhejoge WAHI set hoga (toggle nahi)" },
        { key: "image", value: "", type: "file", description: "Nayi image (optional)" },
      ],
    },
    desc: describe({
      tag: TAG.BREAKING,
      summary: "Category edit karta hai.",
      auth: AUTH_VENDOR,
      when: ["Catalog → Edit category."],
      notes: [
        "**⚠️ BREAKING — `isActive` ka behaviour badal gaya hai.** Pehle `isActive` bhejne pa server current value ko **ulta** kar deta tha (toggle). Yaani `isActive: true` bhejne pe active category **inactive** ho jati thi. Ab jo bhejoge **wahi set** hota hai.",
        "Panel me switch ki nayi value bhejo (`true` = active karo, `false` = deactivate karo) — purana 'bas field bhej do' wala code hata do.",
        "`isActive` na bhejo to value waisi hi rehti hai.",
        "`multipart/form-data` hai (image ke liye). Sirf text badalna ho to bhi form-data hi bhejo, `image` field disable kar do.",
      ],
      fields: [
        ["name", "string", "no", "`Rice & Grains`"],
        ["description", "string", "no", "max 300 chars"],
        ["isActive", "boolean", "no", "`true`/`false` — **set**, toggle nahi"],
        ["image", "file", "no", "Nayi image"],
      ],
      errors: [E.NOT_FOUND, E.VALIDATION, E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  {
    id: "vend.cat.delete",
    group: "03 Catalog · Categories",
    name: "10 · Category delete",
    method: "DELETE",
    path: "/categories/delete/{{categoryId}}",
    auth: "vendorToken",
    tag: TAG.CHANGED,
    desc: describe({
      tag: TAG.CHANGED,
      summary: "Category soft-delete karta hai.",
      auth: AUTH_VENDOR,
      notes: [
        "Doosre vendor ki category delete karne ki koshish → `404`.",
        "Soft delete hai — purane orders ka data safe rehta hai.",
      ],
      errors: [E.NOT_FOUND, E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  // ══════════════════════════════════════════════════════════════
  {
    id: "vend.sub.create",
    group: "04 Catalog · SubCategories",
    name: "11 · SubCategory banao",
    method: "POST",
    path: "/subCategories/{{categoryId}}/create",
    auth: "vendorToken",
    tag: TAG.CHANGED,
    body: {
      type: "formdata",
      fields: [
        { key: "name", value: "Basmati Rice", type: "text", description: "3–120 chars, required" },
        { key: "description", value: "Long grain basmati — 1kg se 25kg tak", type: "text", description: "max 300" },
        { key: "isActive", value: "true", type: "text", description: "`true` | `false`" },
        { key: "image", value: "", type: "file", description: "Icon (optional)" },
      ],
    },
    desc: describe({
      tag: TAG.CHANGED,
      summary: "Kisi category ke andar subcategory banata hai.",
      auth: AUTH_VENDOR,
      when: ["Category banane ke baad, product banane se pehle."],
      notes: [
        "Parent category URL me hai (`/subCategories/:categoryId/create`), body me nahi.",
        "**Parent category aapki honi chahiye** — doosre vendor ki category ka id daala to `404`.",
        "`multipart/form-data`.",
      ],
      fields: [
        ["name", "string", "yes", "`Basmati Rice`"],
        ["description", "string", "no", "max 300"],
        ["isActive", "boolean", "no", "default `true`"],
        ["image", "file", "no", "jpg/png"],
      ],
      errors: [E.NOT_FOUND, E.VALIDATION, E.UNAUTH],
    }),
    script: saveId("subCategoryId", "data", 201),
  },

  {
    id: "vend.sub.getAll",
    group: "04 Catalog · SubCategories",
    name: "12 · Meri subcategories",
    method: "GET",
    path: "/subCategories/getAll",
    auth: "vendorToken",
    tag: TAG.CHANGED,
    query: paging([
      { key: "categoryId", value: "{{categoryId}}", description: "Parent se filter", disabled: true },
    ]),
    desc: describe({
      tag: TAG.CHANGED,
      summary: "Vendor ki apni subcategories.",
      auth: AUTH_VENDOR,
      errors: [E.UNAUTH],
    }),
    script: saveFirstId("subCategoryId", "data.data"),
  },

  {
    id: "vend.sub.get",
    group: "04 Catalog · SubCategories",
    name: "13 · Ek subcategory",
    method: "GET",
    path: "/subCategories/get/{{subCategoryId}}",
    auth: "vendorToken",
    tag: TAG.CHANGED,
    desc: describe({
      tag: TAG.CHANGED,
      summary: "Ek subcategory ki detail.",
      auth: AUTH_VENDOR,
      errors: [E.NOT_FOUND, E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  {
    id: "vend.sub.update",
    group: "04 Catalog · SubCategories",
    name: "14 · ⚠️ SubCategory update (isActive ab SET hai)",
    method: "PUT",
    path: "/subCategories/update/{{subCategoryId}}",
    auth: "vendorToken",
    tag: TAG.BREAKING,
    body: {
      type: "formdata",
      fields: [
        { key: "name", value: "Basmati Rice", type: "text", description: "3–120 chars" },
        { key: "description", value: "Long grain basmati — 1kg se 25kg tak", type: "text", description: "max 300" },
        { key: "categoryId", value: "{{categoryId}}", type: "text", description: "Doosri category me move karna ho to" },
        { key: "isActive", value: "false", type: "text", description: "Jo bhejoge WAHI set hoga" },
        { key: "image", value: "", type: "file", description: "Nayi image" },
      ],
    },
    desc: describe({
      tag: TAG.BREAKING,
      summary: "SubCategory edit karta hai.",
      auth: AUTH_VENDOR,
      notes: [
        "**⚠️ BREAKING — `isActive` ab toggle nahi, set hai** (category ki tarah hi).",
        "`categoryId` bhej ke subcategory ko doosri category me move kar sakte ho — par wo category bhi aapki honi chahiye.",
      ],
      fields: [
        ["name", "string", "no", "`Basmati Rice`"],
        ["description", "string", "no", "max 300"],
        ["categoryId", "ObjectId", "no", "Nayi parent category"],
        ["isActive", "boolean", "no", "**set**, toggle nahi"],
        ["image", "file", "no", "Nayi image"],
      ],
      errors: [E.NOT_FOUND, E.VALIDATION, E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  {
    id: "vend.sub.delete",
    group: "04 Catalog · SubCategories",
    name: "15 · SubCategory delete",
    method: "DELETE",
    path: "/subCategories/delete/{{subCategoryId}}",
    auth: "vendorToken",
    tag: TAG.CHANGED,
    desc: describe({
      tag: TAG.CHANGED,
      summary: "SubCategory soft-delete karta hai.",
      auth: AUTH_VENDOR,
      errors: [E.NOT_FOUND, E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  // ══════════════════════════════════════════════════════════════
  {
    id: "vend.prod.create",
    group: "05 Catalog · Products",
    name: "16 · Product banao (price + stock yahin)",
    method: "POST",
    path: "/products/create",
    auth: "vendorToken",
    tag: TAG.CHANGED,
    body: {
      type: "formdata",
      fields: [
        { key: "name", value: "India Gate Classic Basmati Rice 5kg", type: "text", description: "3–100 chars, required" },
        { key: "brand", value: "India Gate", type: "text", description: "3–80 chars, required" },
        { key: "subCategoryId", value: "{{subCategoryId}}", type: "text", description: "required" },
        { key: "description", value: "Premium aged long grain basmati, 5kg pack", type: "text", description: "max 500" },
        { key: "type", value: "grocery", type: "text", description: "`grocery` | `electronics` | `clothing`" },
        { key: "generalPrice", value: "749", type: "text", description: "₹ — required" },
        { key: "stockQuantity", value: "40", type: "text", description: "units — required" },
        { key: "weightInKg", value: "5", type: "text", description: "kg — required, delivery charge me lagta hai" },
        { key: "isActive", value: "true", type: "text", description: "`true` | `false`" },
        { key: "image", value: "", type: "file", description: "Product photo (optional)" },
      ],
    },
    desc: describe({
      tag: TAG.CHANGED,
      summary: "Naya product banata hai — price aur stock isi document pe.",
      auth: AUTH_VENDOR,
      when: ["Category + subcategory ban jaane ke baad."],
      notes: [
        "**Sabse bada change:** pehle price aur stock alag `ProductLocation` collection me location-wise rehte the. Wo model **delete ho chuka hai** — ab `generalPrice` aur `stockQuantity` seedha product pe hain. Ye single source of truth hai.",
        "**Removed endpoints:** `PUT /products/update-product-locations/:productId` aur `DELETE /products/remove-product-locations/:productId` ab hain hi nahi.",
        "`weightInKg` sirf label nahi hai — delivery charge ke `perKgRate` calculation me seedha lagta hai. Sahi bharo.",
        "`userId` body me mat bhejo — token se lagta hai.",
        "`multipart/form-data`; image optional.",
        "Order place hote hi is product ka `name`, `brand`, `SKU`, `image`, `weightInKg` order ke `productSnapshot` me copy ho jate hain — baad me product badalne se purane order nahi badalte.",
      ],
      fields: [
        ["name", "string", "yes", "`India Gate Classic Basmati Rice 5kg`"],
        ["brand", "string", "yes", "`India Gate` — 3 se 80 chars"],
        ["subCategoryId", "ObjectId", "yes", "`{{subCategoryId}}`"],
        ["generalPrice", "number", "yes", "`749` — bechne wali price"],
        ["stockQuantity", "number", "yes", "`40`"],
        ["weightInKg", "number", "yes", "`5`"],
        ["description", "string", "no", "max 500 chars"],
        ["type", "enum", "no", "`grocery` (default)"],
        ["isActive", "boolean", "no", "default `true`"],
        ["image", "file", "no", "jpg/png"],
      ],
      enums: [["type", "`grocery` · `electronics` · `clothing`", "Product ka type"]],
      errors: [E.VALIDATION, E.NOT_FOUND, E.UNAUTH],
    }),
    script: saveId("productId", "data", 201),
  },

  {
    id: "vend.prod.getAll",
    group: "05 Catalog · Products",
    name: "17 · Mere products",
    method: "GET",
    path: "/products/getAll",
    auth: "vendorToken",
    tag: TAG.CHANGED,
    query: paging([
      { key: "subCategoryId", value: "{{subCategoryId}}", description: "Filter", disabled: true },
      { key: "minStock", value: "0", description: "Stock range", disabled: true },
      { key: "maxStock", value: "5", description: "Low-stock report ke liye", disabled: true },
      { key: "isActive", value: "true", description: "Sirf active", disabled: true },
    ]),
    desc: describe({
      tag: TAG.CHANGED,
      summary: "Vendor ke apne products — inventory screen.",
      auth: AUTH_VENDOR,
      notes: [
        "`?maxStock=5` se 'low stock' report bana sakte ho.",
        "`productLocations[]` array response se hat gaya hai.",
        "`sortBy` valid values: `generalPrice`, `createdAt`, `stockQuantity`, `weightInKg`.",
      ],
      errors: [E.UNAUTH],
    }),
    script: saveFirstId("productId", "data.data"),
  },

  {
    id: "vend.prod.get",
    group: "05 Catalog · Products",
    name: "18 · Ek product",
    method: "GET",
    path: "/products/get/{{productId}}",
    auth: "vendorToken",
    tag: TAG.CHANGED,
    desc: describe({
      tag: TAG.CHANGED,
      summary: "Ek product ki detail (edit form ke liye).",
      auth: AUTH_VENDOR,
      errors: [E.NOT_FOUND, E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  {
    id: "vend.prod.update",
    group: "05 Catalog · Products",
    name: "19 · Product update (price / stock badalna)",
    method: "PUT",
    path: "/products/update/{{productId}}",
    auth: "vendorToken",
    tag: TAG.CHANGED,
    body: {
      type: "formdata",
      fields: [
        { key: "name", value: "India Gate Classic Basmati Rice 5kg", type: "text", description: "3–100 chars" },
        { key: "brand", value: "India Gate", type: "text", description: "3–80 chars" },
        { key: "generalPrice", value: "799", type: "text", description: "Nayi price" },
        { key: "stockQuantity", value: "25", type: "text", description: "Naya stock" },
        { key: "weightInKg", value: "5", type: "text", description: "kg" },
        { key: "subCategoryId", value: "{{subCategoryId}}", type: "text", description: "Move karna ho to" },
        { key: "isActive", value: "true", type: "text", description: "Jo bhejoge wahi set hoga" },
        { key: "isOutOfStock", value: "false", type: "text", description: "Manual out-of-stock flag" },
        { key: "image", value: "", type: "file", description: "Nayi photo" },
      ],
    },
    desc: describe({
      tag: TAG.CHANGED,
      summary: "Product ki price, stock ya detail badalta hai.",
      auth: AUTH_VENDOR,
      when: ["Roz ka kaam — stock aur rate update."],
      notes: [
        "Price/stock ab yahi se badalte hain — purane `update-product-locations` endpoints hata diye gaye hain.",
        "`isOutOfStock: true` se stock hote hue bhi product ko manually out-of-stock dikha sakte ho.",
        "Saare fields optional — jo bhejoge wahi badlega.",
        "`multipart/form-data`.",
      ],
      fields: [
        ["name / brand / description", "string", "no", "Text fields"],
        ["generalPrice", "number", "no", "`799`"],
        ["stockQuantity", "number", "no", "`25`"],
        ["weightInKg", "number", "no", "`5`"],
        ["subCategoryId", "ObjectId", "no", "Doosri subcategory me move"],
        ["type", "enum", "no", "`grocery` · `electronics` · `clothing`"],
        ["isActive", "boolean", "no", "**set**, toggle nahi"],
        ["isOutOfStock", "boolean", "no", "Manual flag"],
        ["image", "file", "no", "Nayi photo"],
      ],
      errors: [E.NOT_FOUND, E.VALIDATION, E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  {
    id: "vend.prod.delete",
    group: "05 Catalog · Products",
    name: "20 · Product delete",
    method: "DELETE",
    path: "/products/delete/{{productId}}",
    auth: "vendorToken",
    tag: TAG.CHANGED,
    desc: describe({
      tag: TAG.CHANGED,
      summary: "Product soft-delete karta hai.",
      auth: AUTH_VENDOR,
      notes: [
        "Soft delete hai — purane orders me `productSnapshot` se naam/photo dikhte rahenge.",
      ],
      errors: [E.NOT_FOUND, E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  // ══════════════════════════════════════════════════════════════
  {
    id: "vend.order.summary",
    group: "06 Orders",
    name: "21 · 🆕 Dashboard summary",
    method: "GET",
    path: "/orders/vendor/summary",
    auth: "vendorToken",
    tag: TAG.NEW,
    desc: describe({
      tag: TAG.NEW,
      summary:
        "Vendor dashboard ka data — total orders, lifetime revenue aur status-wise counts.",
      auth: AUTH_VENDOR,
      when: ["Login ke baad dashboard screen."],
      notes: [
        "`statusCounts` se dashboard pe tiles banao — sabse kaam ka `PENDING` hai (inhe vendor ne abhi tak dekha nahi).",
        "`lifetimeRevenue` me sirf DELIVERED orders count hote hain.",
        "Stage pe Nagraj Mart ka apna poora order history isi me dikhega.",
      ],
      errors: [E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  {
    id: "vend.order.getAll",
    group: "06 Orders",
    name: "22 · Mere orders (order queue)",
    method: "GET",
    path: "/orders/getAll",
    auth: "vendorToken",
    tag: TAG.CHANGED,
    query: paging([
      { key: "status", value: "PENDING", description: "Naye orders ki queue" },
      { key: "deliveryPincode", value: "577001", description: "Pincode se filter", disabled: true },
      { key: "fromDate", value: "2026-09-01", description: "ISO date", disabled: true },
      { key: "toDate", value: "2026-09-30", description: "ISO date", disabled: true },
      { key: "minPayableAmount", value: "500", description: "Amount range", disabled: true },
    ]),
    desc: describe({
      tag: TAG.CHANGED,
      summary: "Vendor ke apne orders — panel ki main screen.",
      auth: AUTH_VENDOR,
      when: ["Orders screen, har status tab ke liye."],
      notes: [
        "Vendor ko hamesha sirf apne orders milte hain — doosre vendor ka order kabhi nahi.",
        "`?status=PENDING` se 'naye orders' tab banao — yahi vendor ka action queue hai.",
        "Har item me `productSnapshot` hai — order ke waqt ka naam/photo. Panel me packing list wahi se banao.",
        "`deliveryAddress` embedded hai — delivery boy ko dene ke liye.",
      ],
      enums: [
        [
          "status",
          "`PENDING` · `ACCEPTED` · `PACKED` · `OUT_FOR_DELIVERY` · `DELIVERED` · `CANCELLED` · `REJECTED`",
          "Filter ke liye",
        ],
      ],
      errors: [E.UNAUTH],
    }),
    script: saveFirstId("orderId", "data.data"),
  },

  {
    id: "vend.order.get",
    group: "06 Orders",
    name: "23 · Order detail",
    method: "GET",
    path: "/orders/get/{{orderId}}",
    auth: "vendorToken",
    tag: TAG.CHANGED,
    desc: describe({
      tag: TAG.CHANGED,
      summary: "Ek order ki poori detail — items, customer, address, pricing, status history.",
      auth: AUTH_VENDOR,
      when: ["Order queue se kisi order pe click karne pe."],
      notes: [
        "Doosre vendor ka order id daala to `404`.",
        "`statusHistory[]` se timeline banao.",
      ],
      errors: [E.NOT_FOUND, E.UNAUTH],
    }),
    script: expectStatus(200),
  },

  {
    id: "vend.order.accept",
    group: "06 Orders",
    name: "24 · 🆕 Status → ACCEPTED (order confirm)",
    method: "PUT",
    path: "/orders/{{orderId}}/status",
    auth: "vendorToken",
    tag: TAG.NEW,
    body: { type: "json", value: { status: "ACCEPTED", note: "Order confirm, packing shuru" } },
    desc: describe({
      tag: TAG.NEW,
      summary:
        "Order ko aage badhata hai. Ye ek hi endpoint saare transitions ke liye hai — sirf `status` badalta hai.",
      auth: AUTH_VENDOR,
      when: ["`PENDING` order pe 'Accept' dabane pe."],
      notes: [
        "**Ye endpoint pehle tha hi nahi.** Purana `PUT /orders/update/:id` (admin-only) **hata diya gaya**.",
        "Server state machine enforce karta hai — galat transition pe `409 INVALID_STATUS_TRANSITION`. Panel me sirf allowed buttons hi dikhao (neeche table).",
        "`REJECTED` pe stock apne aap wapas chala jata hai.",
        "Har transition pe customer ko push notification jaati hai aur `statusHistory[]` me entry add hoti hai.",
        "`note` optional hai — vendor ka internal note. `reason` `REJECTED` ke liye use karo.",
      ],
      fields: [
        ["status", "enum", "yes", "`ACCEPTED` — target status"],
        ["note", "string", "no", "max 300 chars"],
        ["reason", "string", "no", "max 300 chars — `REJECTED` pe zaroori jaisa"],
      ],
      enums: [
        [
          "status",
          "`ACCEPTED` · `PACKED` · `OUT_FOR_DELIVERY` · `DELIVERED` · `REJECTED`",
          "Vendor ke allowed targets",
        ],
      ],
      errors: [E.INVALID_STATUS_TRANSITION, E.NOT_FOUND, E.FORBIDDEN],
      extra: [
        "### Allowed transitions (server enforce karta hai)",
        "",
        "| Abhi | Vendor | Customer | Admin |",
        "|---|---|---|---|",
        "| `PENDING` | `ACCEPTED`, `REJECTED` | `CANCELLED` | — |",
        "| `ACCEPTED` | `PACKED`, `REJECTED` | `CANCELLED` | — |",
        "| `PACKED` | `OUT_FOR_DELIVERY` | — | — |",
        "| `OUT_FOR_DELIVERY` | `DELIVERED` | — | — |",
        "| `DELIVERED` | — | — | — |",
        "| `CANCELLED` / `REJECTED` | — | — | — |",
        "| `CONFIRMED` *(legacy)* | `PACKED`, `REJECTED` | `CANCELLED` | — |",
        "",
        "**Admin ka column poora khaali hai** — admin sirf dekh sakta hai, order aage nahi badha sakta.",
        "Isliye vendor kuch na kare to order `PENDING` me hi pada rahega; admin vendor ko call karega.",
      ].join("\n"),
    }),
    script: expectStatus(200),
  },

  {
    id: "vend.order.pack",
    group: "06 Orders",
    name: "25 · Status → PACKED",
    method: "PUT",
    path: "/orders/{{orderId}}/status",
    auth: "vendorToken",
    tag: TAG.NEW,
    body: { type: "json", value: { status: "PACKED", note: "3 items pack ho gaye" } },
    desc: describe({
      tag: TAG.NEW,
      summary: "Order pack ho gaya.",
      auth: AUTH_VENDOR,
      when: ["`ACCEPTED` order pe — packing complete hone pe."],
      notes: [
        "Sirf `ACCEPTED` (ya legacy `CONFIRMED`) se hi `PACKED` me ja sakte ho.",
        "**`PACKED` hote hi customer ka cancel button band ho jata hai** — iske baad customer cancel nahi kar sakta.",
      ],
      fields: [
        ["status", "enum", "yes", "`PACKED`"],
        ["note", "string", "no", "max 300"],
      ],
      errors: [E.INVALID_STATUS_TRANSITION, E.NOT_FOUND],
    }),
    script: expectStatus(200),
  },

  {
    id: "vend.order.out",
    group: "06 Orders",
    name: "26 · Status → OUT_FOR_DELIVERY",
    method: "PUT",
    path: "/orders/{{orderId}}/status",
    auth: "vendorToken",
    tag: TAG.NEW,
    body: {
      type: "json",
      value: { status: "OUT_FOR_DELIVERY", note: "Delivery ke liye nikal gaya" },
    },
    desc: describe({
      tag: TAG.NEW,
      summary: "Order delivery pe nikal gaya.",
      auth: AUTH_VENDOR,
      when: ["`PACKED` order pe — delivery boy ko dene pe."],
      notes: [
        "Sirf `PACKED` se hi yahan aa sakte ho.",
        "`assignedTo` / `assignedAt` fields DB me reserve hain (delivery boy assignment future ke liye) par abhi koi API nahi hai — inhe ignore karo.",
      ],
      fields: [
        ["status", "enum", "yes", "`OUT_FOR_DELIVERY`"],
        ["note", "string", "no", "max 300"],
      ],
      errors: [E.INVALID_STATUS_TRANSITION, E.NOT_FOUND],
    }),
    script: expectStatus(200),
  },

  {
    id: "vend.order.delivered",
    group: "06 Orders",
    name: "27 · Status → DELIVERED (flow ka aakhri step)",
    method: "PUT",
    path: "/orders/{{orderId}}/status",
    auth: "vendorToken",
    tag: TAG.NEW,
    body: { type: "json", value: { status: "DELIVERED", note: "Cash mil gaya" } },
    desc: describe({
      tag: TAG.NEW,
      summary: "Order deliver ho gaya — flow yahan khatam.",
      auth: AUTH_VENDOR,
      when: ["`OUT_FOR_DELIVERY` order pe — customer ko de dene pe."],
      notes: [
        "Sirf `OUT_FOR_DELIVERY` se hi `DELIVERED` me ja sakte ho.",
        "`deliveredAt` timestamp set ho jata hai.",
        "COD hai isliye payment collect delivery pe hi hoti hai — `paymentStatus` `NOT_REQUIRED` hi rehta hai.",
        "`DELIVERED` **final** hai — iske baad koi transition nahi.",
        "Ye order `lifetimeRevenue` me count hone lagta hai.",
      ],
      fields: [
        ["status", "enum", "yes", "`DELIVERED`"],
        ["note", "string", "no", "max 300"],
      ],
      errors: [E.INVALID_STATUS_TRANSITION, E.NOT_FOUND],
    }),
    script: expectStatus(200),
  },

  {
    id: "vend.order.reject",
    group: "06 Orders",
    name: "28 · Status → REJECTED (stock wapas)",
    method: "PUT",
    path: "/orders/{{orderId}}/status",
    auth: "vendorToken",
    tag: TAG.NEW,
    body: {
      type: "json",
      value: { status: "REJECTED", reason: "Stock khatam ho gaya, sorry" },
    },
    desc: describe({
      tag: TAG.NEW,
      summary: "Vendor order reject karta hai. Stock apne aap wapas add ho jata hai.",
      auth: AUTH_VENDOR,
      when: ["`PENDING` ya `ACCEPTED` order pe — stock na ho ya deliver na kar sako."],
      notes: [
        "`PACKED` ke baad reject nahi kar sakte.",
        "Har item ka stock guarded `$inc` se wapas add hota hai.",
        "`reason` customer ko dikhta hai — bharna chahiye.",
        "Customer ko push notification jaati hai.",
      ],
      fields: [
        ["status", "enum", "yes", "`REJECTED`"],
        ["reason", "string", "no", "`Stock khatam ho gaya, sorry` — max 300"],
      ],
      errors: [E.INVALID_STATUS_TRANSITION, E.NOT_FOUND],
    }),
    script: expectStatus(200),
  },
];
